name: test_spread_radius

on:
  workflow_dispatch:
  push:
    branches: [main, bitrot]
  pull_request:
    branches: [main, bitrot]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: test_spread_radius
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.12
          auto-activate-base: false

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
      - name: Install Eigen
        run: sudo apt-get update && sudo apt-get install -y libeigen3-dev

      - name: make C++
        run: |
          cd cell2fire/Cell2FireC
          make

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
          pip install pytest

      - name: setup the program
        run: |
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: run tests
        run: |
          cd tests
          pytest test_spread_radius.py
